name: main
on: push

jobs:
  build:
    name: Build-n-stuff
    runs-on: ubuntu-latest
    container:
      image: docker.io/saxofon/yocto-builder:0.4
      options: --user 1000
    steps:
      - uses: actions/checkout@v1

      - name: Workaround to allow action to run as non-root
        run: sudo chmod 777 .

      - name: build
        run: make images
